"use client";

import { FormEvent, useEffect, useState } from "react";

const configuredApi = process.env.NEXT_PUBLIC_API_URL;
const apiBase = () => configuredApi ?? (typeof window === "undefined" ? "http://localhost:3000" : `${window.location.protocol}//${window.location.hostname}:3000`);

export default function AcceptInvitePage() {
  const [invite, setInvite] = useState<{ email: string; name?: string; role: string } | null>(null);
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [message, setMessage] = useState("Checking invitation…");
  const token = typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("token") || "";
  useEffect(() => { if (!token) return setMessage("This invitation link is missing."); fetch(`${apiBase()}/auth/invitations/${encodeURIComponent(token)}`).then(async response => { const data = await response.json(); if (!response.ok) throw Error(data.message); setInvite(data); setMessage(""); }).catch(error => setMessage(error.message)); }, [token]);
  const partnerDeepLink = `caviteexplorer://accept-invite?token=${encodeURIComponent(token)}`;
  const partnerIntentLink = `intent://accept-invite?token=${encodeURIComponent(token)}#Intent;scheme=caviteexplorer;package=com.example.cavite_explorer_mobile;end`;
  const submit = async (event: FormEvent) => { event.preventDefault(); if (password.length < 8) return setMessage("Use at least 8 characters."); if (password !== confirm) return setMessage("Passwords do not match."); const response = await fetch(`${apiBase()}/auth/invitations/accept`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, password }) }); const data = await response.json().catch(() => ({})); if (!response.ok) return setMessage(data.message || "Could not create your account."); const login = await fetch(`${apiBase()}/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: invite?.email, password }) }); const loginData = await login.json().catch(() => ({})); if (!login.ok) return setMessage("Account created. Verify your email if requested, then sign in to the admin portal."); const profile = await fetch(`${apiBase()}/auth/me`, { headers: { Authorization: `Bearer ${loginData.token}` } }).then(result => result.json()); sessionStorage.setItem("admin_token", loginData.token); sessionStorage.setItem("admin_role", profile.user?.role || "editor"); window.location.assign("/"); };
  const eyeStyle = { position: "absolute" as const, right: 10, top: "50%", transform: "translateY(-50%)", border: 0, background: "transparent", color: "#14674f", padding: 4, fontSize: 12, fontWeight: 700 };
  const fieldStyle = { position: "relative" as const };
  const inputStyle = { paddingRight: 46 };
  if (invite?.role === "partner") return <main className="login-page"><div className="login-art"><p className="brand-kicker">CAVITE EXPLORER</p><h1>Your partner workspace starts on mobile.</h1><p>Create your password in the Cavite Explorer Android app, then submit your business profile and location for approval.</p></div><section className="login-card"><div className="login-mark">CE</div><p className="eyebrow">PARTNER INVITATION</p><h2>Continue in the app</h2><p className="login-copy">This invitation is for <strong>{invite.email}</strong>.</p><a className="primary partner-invite-open" href={partnerIntentLink}>Open Cavite Explorer</a><p className="login-copy partner-invite-help">Android should ask to open Cavite Explorer. If it does not, confirm the app is installed and try the direct link below.</p><a className="partner-direct-link" href={partnerDeepLink}>Try direct app link</a></section></main>;
  return <main className="login-page"><div className="login-art"><p className="brand-kicker">CAVITE EXPLORER</p><h1>You’re invited to help keep Cavite exploring.</h1><p>Create your own password to activate your invited workspace access.</p></div><section className="login-card"><div className="login-mark">CE</div><p className="eyebrow">TEAM INVITATION</p><h2>{invite ? `Join as ${invite.role}` : "Invitation"}</h2>{invite && <p className="login-copy">{invite.name ? `${invite.name}, ` : ""}this invitation is for <strong>{invite.email}</strong>.</p>}{invite && <form onSubmit={submit}><label>Create password<div className="password-field" style={fieldStyle}><input style={inputStyle} type={showPassword ? "text" : "password"} value={password} onChange={event => setPassword(event.target.value)} required /><button aria-label={showPassword ? "Hide password" : "Show password"} style={eyeStyle} type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? "Hide" : "Show"}</button></div></label><label>Confirm password<div className="password-field" style={fieldStyle}><input style={inputStyle} type={showPassword ? "text" : "password"} value={confirm} onChange={event => setConfirm(event.target.value)} required /><button aria-label={showPassword ? "Hide password" : "Show password"} style={eyeStyle} type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? "Hide" : "Show"}</button></div></label><button className="primary wide">Create account →</button></form>}{message && <p className="form-message">{message}</p>}</section></main>;
}
